import React from 'react'
import Head from 'next/head'

export const config = {
  amp: true,
}

const example: React.FC = () => {
  return (
    <div className="min-h-screen p-2.5 ">
      <Head>
        <title>dl10yr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 

      <main className="flex flex-wrap">
        <div className="w-full lg:w-2/3">
          <div className="p-3">
            <h2 className="text-red-700 font-bold  text-center"> Bu bir Amp Test Sayfasıdır Denemedir yani</h2>
          </div>
        </div>
      
      </main>
    </div>
  )
}

export default example
