import React from 'react'
import Head from 'next/head'

export const config = {
  amp: true,
}

const example: React.FC = () => {
  return (
    <div className="min-h-screen p-2.5 ">
      <Head>
        <title>dl10yr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://amp123213.vercel.app/" rel="canonical"/>

      </Head>
 

      <main className="flex flex-wrap">
        <div className="w-full lg:w-2/3">
          <div className="p-3">
            <h2 className="text-red-700 font-bold  text-center"> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</h2>
         
         
          </div>
        </div>
      
      </main>
    </div>
  )
}

export default example
